version: "3.8"

services:
  database:
    container_name: pgsql-ecommercedb
    image: postgres:10-alpine
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=ecommercedb
    restart: on-failure