version: "3.8"

services:
  database:
    container_name: pgsql-ecommercedb
    image: postgres:10-alpine
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=ecommercedb
    restart: on-failure
    networks:
      - local_network

  webservice:
    container_name: webservice
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    networks:
      - local_network
    depends_on:
      - database
    
networks:
  local_network:
    name: local_network
